easy_admin:
    user:
        display_name: false
    entities:
        Product:
            class: App\Entity\Product
            new:
                fields:
                    - 'styleNumber'
                    - 'name'
                    - 'images'
                    - {property: 'price', type: 'App\Form\PriceType'}
            edit:
                fields:
                    - 'styleNumber'
                    - 'name'
                    - 'images'
                    - {property: 'price', type: 'App\Form\PriceType'}
        Catalog:
            class: App\Entity\Catalog
            list:
                actions: ['-edit']
                disabled_actions: ['edit']
            new:
                fields:
                    - {property: 'file', label: 'File', type: 'Vich\UploaderBundle\Form\Type\VichFileType'}

    site_name: Php Challenge
    design:
        menu:
            - { entity: 'Catalog', label: 'Catalogs', icon: 'archive' }
            - { entity: 'Product', label: 'Products', icon: 'tshirt' }