version: '3.7'

services:
  app:
    build: ./docker
    volumes:
      - ./:/var/www/html:delegated
    ports:
      - 80:80
    environment:
      DATABASE_URL: mysql://root:password123@mysql:3306/php_challenge
      MESSENGER_TRANSPORT_DSN: amqp://guest:guest@rabbitmq:5672/%2f/messages
  mysql:
    image: mysql:8.0.23
    environment:
      MYSQL_ROOT_PASSWORD: password123
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
  rabbitmq:
    image: rabbitmq:3.8.11
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
